dist: xenial
language: node_js
#node_js:
#  - "stable"
#before_install:
#  - npm install
#script :
#  - npm run-script build
before_install:
#  - tar cvf $SCOUTER_PAPER_COMPRESS_NAME build/
  - echo -e "Host $DEMO_SERVER_NODE\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "$DEMO_DEPLOY_KEY" | tr -d '\r' > $DEMO_DELOY_FILE
  - chmod 600 $DEMO_DELOY_FILE
  - echo "scp -i $DEMO_DELOY_FILE $SCOUTER_PAPER_COMPRESS_NAME $DEMO_SERVER_USER@$DEMO_SERVER_NODE:/home/$DEMO_SERVER_USER"
  - scp -i $DEMO_DELOY_FILE README.md $DEMO_SERVER_USER@$DEMO_SERVER_NODE:/home/$DEMO_SERVER_USER
#  - echo "ssh -i $DEMO_DELOY_FILE -T $DEMO_SERVER_USER@$DEMO_SERVER_NODE"
#  - ssh -i $DEMO_DELOY_FILE -o StringHostKeyChecking=no -T $DEMO_SERVER_USER@$DEMO_SERVER_NODE "/home/ec2-user/deploy.sh $SCOUTER_PAPER_COMPRESS_NAME"
cache:
  directories:
    - "node_modules"
branches:
  only:
    - development
    - master
notifications:
  slack: scouterapm:fJndRYgbQA0uTLXiEqxZJhUU

#: construction_worker:
# job life cycle explain : https://docs.travis-ci.com/user/job-lifecycle/